set -e
true
true
/home/ephraim/miniconda3/envs/spades/bin/spades-core /home/ephraim/spades_isolate_output/K21/configs/config.info /home/ephraim/spades_isolate_output/K21/configs/isolate_mode.info
/home/ephraim/miniconda3/envs/spades/bin/spades-core /home/ephraim/spades_isolate_output/K33/configs/config.info /home/ephraim/spades_isolate_output/K33/configs/isolate_mode.info
/home/ephraim/miniconda3/envs/spades/bin/spades-core /home/ephraim/spades_isolate_output/K55/configs/config.info /home/ephraim/spades_isolate_output/K55/configs/isolate_mode.info
/home/ephraim/miniconda3/envs/spades/bin/spades-core /home/ephraim/spades_isolate_output/K77/configs/config.info /home/ephraim/spades_isolate_output/K77/configs/isolate_mode.info
/home/ephraim/miniconda3/envs/spades/bin/python3 /home/ephraim/miniconda3/envs/spades/share/spades/spades_pipeline/scripts/copy_files.py /home/ephraim/spades_isolate_output/K77/before_rr.fasta /home/ephraim/spades_isolate_output/before_rr.fasta /home/ephraim/spades_isolate_output/K77/assembly_graph_after_simplification.gfa /home/ephraim/spades_isolate_output/assembly_graph_after_simplification.gfa /home/ephraim/spades_isolate_output/K77/final_contigs.fasta /home/ephraim/spades_isolate_output/contigs.fasta /home/ephraim/spades_isolate_output/K77/first_pe_contigs.fasta /home/ephraim/spades_isolate_output/first_pe_contigs.fasta /home/ephraim/spades_isolate_output/K77/strain_graph.gfa /home/ephraim/spades_isolate_output/strain_graph.gfa /home/ephraim/spades_isolate_output/K77/scaffolds.fasta /home/ephraim/spades_isolate_output/scaffolds.fasta /home/ephraim/spades_isolate_output/K77/scaffolds.paths /home/ephraim/spades_isolate_output/scaffolds.paths /home/ephraim/spades_isolate_output/K77/assembly_graph_with_scaffolds.gfa /home/ephraim/spades_isolate_output/assembly_graph_with_scaffolds.gfa /home/ephraim/spades_isolate_output/K77/assembly_graph.fastg /home/ephraim/spades_isolate_output/assembly_graph.fastg /home/ephraim/spades_isolate_output/K77/final_contigs.paths /home/ephraim/spades_isolate_output/contigs.paths
true
/home/ephraim/miniconda3/envs/spades/bin/python3 /home/ephraim/miniconda3/envs/spades/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/ephraim/spades_isolate_output/scaffolds.fasta --misc_dir /home/ephraim/spades_isolate_output/misc --threshold_for_breaking_scaffolds 3
true
